danielfrg/pelican-jupyter

README.md, ipynb.py
A new Boolean option in pelicanconf.py, `IPYNB_USE_META_SUMMARY`, can trigger using the summary from the `.ipynb-meta` file, instead of creating it from the notebook.
=>   Added option for using the summary in the .ipynb-meta file 

ipynb.py
Jupyter changes the layout of modules. This commit tries to default to this structure, and failing so it tries importing the older IPython modules.
=> Jupyter compatible

README.md, requirements.txt
Hi,
thanks for maintaining this, it's a really neat addition to pelican.
As a suggestion, you may want to document the dependency on Beautiful Soup - I was quite confused for a little while because I couldn't get the `#ignore` functionality to work, and the failsafe BS4 import means that you'll never see an error message. This PR also adds a requirements.txt file which gets things up and running in a fresh virtualenv.
=> Add beautifulsoup4 to list of dependencies.

core.py, markup.py
using python2.X causes UnicodeDecodeError.
line85 in markup.py needs .decode("utf-8").
and bs4 warns this:
---
UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
To get rid of this warning, change this:
BeautifulSoup([your markup])
to this:
BeautifulSoup([your markup], "html.parser")
---
so,line85 in core.py should be BeautifulSoup(content,"html.parser")
=> edit for python 2.X

markup.py
.format() is using 'ascii' encoding which results in errors of the form
```
ERROR: Could not process ./test2.ipynb
| UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 112: ordinal not in range(128)
```
=> Fix: resolves UnicodeEncodeError from non ascii characters

markup.py
Somewhere along the commits, this configuration option went missing.
=> IPYNB_USE_META_SUMMARY option is no longer ignored

markup.py
When using the plugin with python 3, I was seeing the following rendering:
This PR, should fix that.
=> Prevent wierd bytestring rendering on py3

markup.py
This fixes issue #54. The first error was a non-error one. I just mistook it for an error because the error message had misplaced encoding.
The second error is in line 87. It appears the check for `content` attribute `decode` was bogus in two ways:
1. `content` here may be `str` or `unicode`. I properly checked the correct type with `six.binary_type`.
2. `content` was being `decoded` and then joined (through `format()`) to a `unicode` string, due to `unicode_literals`. This causes `format()` to try to decode the just-encoded bytes as ASCII, causing the error.
`six` as a new dependency shouldn't be a problem since it is [recommended by the Pelican contributors blog](http://blog.getpelican.com/pelicans-unified-codebase.html) and is also used by Pelican itself.
=> Fix UnicodeEncodeError in issue #54

core.py, liquid.py
This brings over the ``cells[start:end]`` syntax from liquid tags. I find this useful when I want to compose a blog post in a notebook, but also have the notebook available for download. Using this I can skip some intro cells (such as the title and a note about the blog post) without needing two copies of the notebook.
=> ENH: allow cells[start:end] in liquid

core.py
Minor change to allow MathJax to break lines -- useful for long equations, especially on mobiles--
=> Allow MathJax to break equations.

README.md
to remove the warning for deprecated string type to array.
=> Update README: PLUGIN_PATH from string to array

markup.py
File discovery will fail when `.ipynb-meta` files contains `.` in the name.
I think the fix is to replace `filename.split('.')[0]` with `os.path.splitext(filename)[0]`
I was having issued when the file was named "04.09.09.post.ipynb", but it works after this fix.
=> Finding ipynb-meta files fails if filename contains '.'

core.py
From #70: [MathJax CDN shutting down on April 30, 2017](https://www.mathjax.org/cdn-shutting-down/). 
Although it is small, the bug is in a sense urgent, I am opening this pull request to fix the bug.
=> fix mathjax cdn

core.py
Fix invalid HTML output when using BeautifulSoup to decode content.
Consider this input cell:
```python
html = """<div><table border="1" class="dataframe"><thead><tr style="text-align:right;"><th></th><th>x</th><th>y</th></tr></thead><tbody><tr><th>0</th><td>-2.863752</td><td>-1.066424</td></tr><tr><th>1</th><td>-0.779238</td><td>0.862169</td></tr></tbody></table></div>"""
```
When decode using `None` formatter with [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#output-formatters)
```python
soup = BeautifulSoup(content, 'html.parser')
content = soup.decode(formatter=None)
```
The HTML value inside string is parsed as table in static file, which is not desired as we want a code block here.
By using `soup.decode(formatter="minimal")` which suggested by …
=> Generate valid HTML for HTML-based strings.

markup.py
pretty straightforward bugfix: if you put summary in metadata to override default summary, pelican-ipynb fails to pick it up because it checks "summary" in the global pelican settings
=> fix: presence of "summary" should be checked in metadata, not pelican settings

README.md, core.py, markup.py
This commit adds support for specifying a list of nbconvert preprocessors to be used when converting the document. 
I ran into an issue when trying to use the [Python Markdown](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/python-markdown/readme.html) nbconvert extension. I needed a way of passing in preprocessors to be used during the conversion from a notebook file to HTML. This PR contains support for a new config option, `IPYNB_PREPROCESSORS`, that expects a list of preprocessors that will be used during the generation of HTML output.
=> Adding support for nbconvert preprocessors

README.md, markup.py
(sorry, accidentally deleted original PR  #89, this is new one, with rebased branch)
Concept based on https://github.com/peijunz/ipynb2pelican, where the metadata is extracted from the first cell of the notebook.
This makes things easier because the metadata can trivially be managed from within the notebook (no need for a separate `.ipynb-meta` file or manually editing the `.ipynb` json)
=> Add new "metacell" option, where metadata is extracted from the first notebook cell

core.py
Hi, 
first, thanks for the plugin.
I am using a rather new version of jupyter and found that the style that nbconvert creates within the html file is not applied for some of the pelican themes, such as pelican-bootstrap3.
One reason is that the nbconvert API may have changed slightly.
Also, the pygments output is wrapped in a pre-tag, which I add to the nbconvert css.
This is not a robust solution as it makes many assumptions and is not configurable, mostly because I am not familiar with all the tools :)
Please let me know what you think.
Thanks!
=> fix for jupyter 4.1.1

core.py
Currently the ipynb plugin creates its own config object, which means that it ignores the nbconvert config that can be found in the user's jupyter profile directory (e.g., `~/.jupyter/jupyter_nbconvert_config.py`) or in the current project directory. This means that the user may experience unexpected behavior when using the plugin if they expect nbconvert to honor their configuration. This PR includes a small bit of code which makes sure that the nbconvert config is loaded and then any additional configuration changes needed by the plugin are merged into the user's config.
=> Adding support for nbconvert configuration

markup.py
Hi
I was getting this error while trying to convert my ipynb.
```
ERROR: Could not process ./Tosser.ipynb
| UnboundLocalError: local variable 'md_reader' referenced before assignment
```
Having a look, this only happens for files that use a markdown cell for the metadata. This was a simple fix and I thought I'd PR this in. 
Let me know if there are any issues/concerns and I can squash for you to merge
=> Fix unbound local error for `md_reader`

__init__.py
Avoid this error:
AttributeError: module 'pelican-ipynb' has no attribute 'register'
=> Fixing import for usage in getpelican/pelican-plugins repo

environment.yml, requirements-package.txt, requirements.txt
This PR aims to temporary fix this issue https://github.com/danielfrg/pelican-jupyter/issues/126
=> Pin nbconvert to be >= 5.x but < 6.x

.github/workflows/test.yml, requirements.txt
=> Fix failing tests
